### PR TITLE
Fix bugs in vle.c and add CLR bridge

### PR DESCRIPTION
**Pull request by prj**
Fixed the bugs with se_ load/store instructions as well as e_stb.
Added C++/CLI interop layer to be able to use the library from the CLR, if required.

### CODE REVIEW

**Comment by prj** [comment]
Tests should be fixed also. They fail because of stuff like this:
{{0x88, 0x18, 0x00, 0x00}, SZ_SE , "se_lbz r1 0x8(r8)"},
a se_ instruction can not access registers r8-r23. This should be "se_lbz r1 0x8(r24)" due to the translation.

**Comment by wargio** [comment]
You can add a special type for this.

**Comment by prj** [comment]
> 
> 
> You can add a special type for this.

You mean for the tests?
I already got a little more than I signed up for :)
I am not sure if you want to accept the C++/CLI interop into this project or not. But I made it, so I figured I'd contribute it. If you don't want the clutter, you can disregard it.
I just needed it to call your library from the CLR.

**Comment by prj** [comment]
Needs more work to be valid...

**Comment by wargio** [comment]
i'm ok for having bindings for C++ actually it looked good. i can wait for your PR if you want. just let me know.

**Comment by prj** [comment]
> 
> 
> i'm ok for having bindings for C++ actually it looked good. i can wait for your PR if you want. just let me know.

Bindings are for Microsoft CLR, so usually for C# and so on.
They are just written in C++/CLI.

From a C# development perspective it looks like this:
```
public class PPCVLEParser {
    public PPCVLEParser();

    public static VLEt DecodeOne(byte[] buf, int adr, uint @base);
}
```

**Comment by wargio** [comment]
Yes i noticed.

**Pull request closed without merging**
